# Alembic Configuration File
# For documentation, see: https://alembic.sqlalchemy.org/en/latest/

[alembic]
# path to migration scripts
sqlalchemy.url = driver://user:password@localhost/dbname
script_location = .

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
#file_template = %%(asctime)s_%%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date
# within the migration file (leave blank for localtime)
# timezone =

# max length of characters to apply to the
# "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment under
# the "in memory" SQLite database. The database
# is discarded when the env exits.
# For testing, this is useful
# sqlalchemy.echo = false

# set to 'false' to suppress autogeneration of
# migration files when there are no changes detected.
compare_type = false
compare_server_default = false

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
